[general]
OPENAI_API_KEY="sk-...only needed in case you use table/image summarization or contextual retreival..."
ANTHROPIC_API_KEY="sk-...only needed in case you use table/image summarization or contextual retreival..."

[default]
api_key="...vectara-api-key..."
