[general]
OPENAI_API_KEY="sk-...only needed for table/image summarization, contextual retreival..."
ANTHROPIC_API_KEY="sk-...only needed for table/image summarization, contextual retreival..."

[default]
api_key="...vectara-api-key..."
