vectara:
  corpus_key: ask-hbs
  reindex: true
  create_corpus: true

crawling:
  crawler_type: website

website_crawler:
  urls: ["https://www.hbs.edu"]
  pos_regex: [".*hbs.edu.*"]
  num_per_second: 1
  pages_source: sitemap
