vectara:
  corpus_id: 173
  customer_id: 1526022105
  reindex: true

crawling:
  crawler_type: website

website_crawler:
  urls: ["https://www.hbs.edu"]
  pos_regex: [".*hbs.edu.*"]
  num_per_second: 1
  pages_source: sitemap
