vectara:
  corpus_key: confluence
  reindex: true
  create_corpus: false

crawling:
  crawler_type: confluencedatacenter

confluencedatacenter:
  # Local Confluence Data Center base URL
  base_url: "http://host.docker.internal:8090"
  
  # CQL query to fetch content from TEST space
  # This will get all pages and blog posts from the TEST space
  confluence_cql: 'space = "TEST" and type IN (page, blogpost)'
  
  # Whether to include attachments in the crawl
  confluence_include_attachments: true
  
  # Optional: Body view to use for content extraction
  # Options: export_view, styled_view, storage, editor
  body_view: "export_view"
  
  # Optional: Limit number of results per API call
  limit: 25

metadata:
  public: true 