vectara:
  corpus_key: folder
  reindex: true
  create_corpus: true

crawling:
  crawler_type: folder

folder_crawler:
  path: "/Users/ofer/Downloads/transformer-papers/"
  extensions: ['.pdf']
  source: 'pdf-folder'

