vectara:
  corpus_key: csv
  reindex: true
  create_corpus: true

crawling:
  crawler_type: csv

csv_crawler:
  file_path: "/Users/some_user/data/Game_of_Thrones_Script.csv"
  doc_id_columns: [Season, Episode]
  text_columns: [Name, Sentence]
  metadata_columns: ["Season", "Episode", "Episode Title"]
