vectara:
  corpus_key: news-fox
  reindex: false
  create_corpus: false

crawling:
  crawler_type: rss

rss_crawler:
  source: fox
  rss_pages: [
    "https://feeds.foxnews.com/foxnews/latest", "https://feeds.foxnews.com/foxnews/national", "http://feeds.foxnews.com/foxnews/world",
    "https://feeds.foxnews.com/foxnews/politics", "https://feeds.foxnews.com/foxnews/business", "https://feeds.foxnews.com/foxnews/entertainment",
    "https://feeds.foxnews.com/foxnews/health", "https://feeds.foxnews.com/foxnews/science", "https://feeds.foxnews.com/foxnews/tech",
    "https://feeds.foxnews.com/foxnews/internal/travel/mixed", "https://feeds.foxnews.com/foxnews/section/lifestyle"
  ]
  days_past: 30
  delay: 1
