vectara:
  corpus_id: 4
  customer_id: 4077139778
  reindex: true

crawling:
  crawler_type: "Qumulo Care"

website_crawler:
  urls: [https://care.qumulo.com]
  pos_regex: ["https://care.qumulo.com/.*"]
  pages_source: crawl
  extraction: playwright
  delay: 1
  max_depth: 3
  ray_workers: 2
