# v.4.3-32417225

vectara:
  corpus_key: Qumulo_Main_5
  customer_id: 4077139778
  reindex: true
  remove_boilerplate: true

crawling:
  crawler_type: website

website_crawler:
  urls: [https://qumulo.com]
  pos_regex: ["^https:\/\/qumulo.com\/?(.*)?$"]
 #neg_regex: [".*care.qumulo.*",".*docs.qumulo.com.*"]
  pages_source: crawl
  extraction: playwright
  delay: 1
  max_depth: 2
 #crawl_report: true
 #timeout: 30
 #post_load_timeout: 30
  ray_workers: 40
  remove_old_content: true
  html_processing:
    ids_to_remove: []
    classes_to_remove: []
    tags_to_remove: []

doc_processing:
  summarize_tables: false
