vectara:
  corpus_id: 28
  customer_id: 1169579801
  reindex: false
  verbose: false

crawling:
  crawler_type: website

website_crawler:
  urls: [https://sf.gov]
  num_per_second: 3
  pos_regex: [".*sf.gov.*"]
  neg_regex: [".*sf.gov/es/.*", ".*sf.gov/fil/.*", ".*sf.gov/zh-hant/.*"]
  pages_source: crawl # options are: (1) 'sitemap' automatically retreived from website (2) 'crawl' for recursive crawling
  max_depth: 3
  ray_workers: 0
