vectara:
  corpus_key: ingest_sharepoint
  reindex: true
  create_corpus: false

crawling:
  crawler_type: sharepoint

sharepoint_crawler:
  team_site_url: "http://ec2amaz-v5pti1f/wplinvm"
  mode: list
  target_list: "P2P Asia Invoices"
  list_item_metadata_properties:
    - Site
    - Supplier
    - PO
    - ID