vectara:
  corpus_key: arxiv-transformers
  reindex: True
  create_corpus: true

crawling:
  crawler_type: arxiv

arxiv_crawler:
  query_terms: ["transformers", "attention", "language model"]
  arxiv_category: cs
  n_papers: 200
  sort_by: citations # citations or date
  start_year: 2017
