vectara:
  corpus_key: gdrive
  reindex: true
  create_corpus: false

crawling:
  crawler_type: gdrive

gdrive_crawler:
  # Use OAuth authentication (single user only)
  # Note: OAuth mode does not require 'delegated_users' field
  # For multi-user crawling, use service account authentication instead
  auth_type: oauth

  # Path to OAuth credentials file
  # This should contain the OAuth token JSON (token, refresh_token, client_id, client_secret, etc.)
  # Generate using: python scripts/gdrive/generate_oauth_token.py
  # See docs/gdrive-oauth-setup.md for detailed setup instructions
  # The token will be automatically refreshed and saved back to this file when it expires
  credentials_file: credentials.json

  # Days back to crawl (files modified in last N days)
  # Default: 7 days if not specified
  days_back: 7

  # Permission filtering
  # Files must be shared with at least one of these to be crawled
  # Default: ['Vectara', 'all'] - only files shared with 'Vectara' group or 'all' (public)
  permissions:
    - Vectara
    - all

  # Optional: Ray workers for parallel processing (default: 0)
  # 0 = no parallelization, >0 = number of workers
  ray_workers: 0
