vectara:
  corpus_key: github
  reindex: true
  create_corpus: false

crawling:
  crawler_type: github

github_crawler:
  owner: "vectara"
  repos: ["getting-started", "protos", "slackbot", "magazine-search-demo", "web-crawler", "Search-UI", "hotel-reviews-demo", "vectara-ingest", "vectara-answer"]
  crawl_code: true
